module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/?(*.)+(spec|test).[tj]s?(x)'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  coverageDirectory: './coverage',
  collectCoverageFrom: ['src/**/*.{ts,js}',
    '!src/**/*.d.ts', 
    '!src/node_modules/**', 
    '!src/dist/**',
    '!src/config/**',
    '!src/database/**',
    '!src/middlewares/**',
    '!src/middlewares/**',
    '!src/index.ts'],
  setupFiles: ['<rootDir>/tests/setupEnv.ts'],
};
